// src/components/svelte/Separator.svelte
<script lang="ts">
  import { componentStyles } from '../shared'

  export let orientation: 'horizontal' | 'vertical' = 'horizontal'
  export let decorative = true
  let className = ''
  export { className as class }
</script>

<div
  class="{componentStyles.separator.base} {orientation === 'horizontal' ? componentStyles.separator.horizontal : componentStyles.separator.vertical} {className}"
  data-orientation={orientation}
  role={decorative ? 'none' : 'separator'}
/>

// src/components/react/ui/Separator.tsx
'use client'

import React from 'react'
import * as SeparatorPrimitive from '@radix-ui/react-separator'
import { componentStyles, cn } from '../../shared'

interface SeparatorProps extends React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root> {
  className?: string
  orientation?: 'horizontal' | 'vertical'
  decorative?: boolean
}

const Separator = React.forwardRef<React.ElementRef<typeof SeparatorPrimitive.Root>, SeparatorProps>(
  (
    { className, orientation = 'horizontal', decorative = true, ...props },
    ref
  ) => (
    <SeparatorPrimitive.Root
      ref={ref}
      decorative={decorative}
      orientation={orientation}
      className={cn(
        componentStyles.separator.base,
        orientation === 'horizontal' ? componentStyles.separator.horizontal : componentStyles.separator.vertical,
        className
      )}
      {...props}
    />
  )
)
Separator.displayName = SeparatorPrimitive.Root.displayName

export { Separator }
