// src/components/svelte/content/AccordionGroup.svelte
<script lang="ts">
  import { componentStyles } from '../../shared';
  import Accordion from '../ui/Accordion.svelte';
  import AccordionItem from '../ui/AccordionItem.svelte';
  import AccordionTrigger from '../ui/AccordionTrigger.svelte';
  import AccordionContent from '../ui/AccordionContent.svelte';
  import { ChevronDown } from 'lucide-svelte';

  let type = $props<'single' | 'multiple'>('single');
  let value = $bindable<string | string[] | undefined>();
  let defaultValue = $props<string | string[]>('');
  let collapsible = $props<boolean>(true);
  let className = $props<string>('');

  let items = $state<Array<{title: string, value: string, icon?: any, children?: any}>>([]);

  $effect(() => {
    const slots = $$slots;
    if (slots && slots.default) {
      // Get children from slot
    }
  });
</script>

<div class={'border rounded-lg overflow-hidden ' + className}>
  <Accordion.Root {type} bind:value {defaultValue} {collapsible} class={componentStyles.accordion.base}>
    <slot />
  </Accordion.Root>
</div>

// src/components/react/content/AccordionGroup.tsx
'use client'

import React, { Children, isValidElement, ReactElement } from 'react'
import * as Icons from 'lucide-react'
import { componentStyles, cn } from '../../shared'
import {
  Accordion as AccordionRoot,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from '../ui/Accordion'

interface AccordionGroupProps {
  children: React.ReactNode
  className?: string
  defaultValue?: string | string[]
  type?: 'single' | 'multiple'
  collapsible?: boolean
}

interface ChildProps {
  title?: string
  children?: React.ReactNode
  icon?: keyof typeof Icons
  value?: string
}

const AccordionGroup: React.FC<AccordionGroupProps> = ({
  children,
  className,
  defaultValue,
  type = 'single',
  collapsible = true,
}) => {
  // Process children to add proper value props and wrap in Radix structure
  const processedChildren = Children.map(children, (child, index) => {
    if (!isValidElement(child)) return null

    const childElement = child as ReactElement<ChildProps>
    const childProps = childElement.props
    const value = childProps.value || `item-${index + 1}`
    const Icon = childProps.icon ? (Icons[childProps.icon] as React.FC<{ className?: string }>) : null

    return (
      <AccordionItem key={value} value={value}>
        <AccordionTrigger className="flex items-center gap-2 px-4 py-3 text-start">
          {Icon && <Icon className="h-4 w-4 shrink-0 text-muted-foreground" />}
          <span className="font-medium text-base">{childProps.title}</span>
        </AccordionTrigger>
        <AccordionContent>
          {childProps.children}
        </AccordionContent>
      </AccordionItem>
    )
  })

  return (
    <div className={cn('border rounded-lg overflow-hidden', className)}>
      {type === 'single' ? (
        <AccordionRoot
          type="single"
          collapsible={collapsible}
          defaultValue={defaultValue as string | undefined}
          className={componentStyles.accordion.base}
        >
          {processedChildren}
        </AccordionRoot>
      ) : (
        <AccordionRoot
          type="multiple"
          defaultValue={defaultValue as string[] | undefined}
          className={componentStyles.accordion.base}
        >
          {processedChildren}
        </AccordionRoot>
      )}
    </div>
  )
}

export default AccordionGroup
