// src/components/svelte/content/Button.svelte
<script lang="ts">
  import { componentStyles } from '../../shared'
  import { getDocuBook } from '../../../adapters/svelte'

  let { 
    href = '', 
    text = '', 
    target = '_self', 
    size = 'md', 
    variation = 'primary', 
    className = '',
    icon
  }: {
    href: string
    text?: string
    target?: '_blank' | '_self' | '_parent' | '_top'
    size?: 'sm' | 'md' | 'lg'
    variation?: 'primary' | 'accent' | 'outline' | 'ghost' | 'link'
    className?: string
    icon?: any
  } = $props()

  let LinkComponent = $derived(getDocuBook()?.Link || null)

  const rel = $derived(target === '_blank' ? 'noopener noreferrer' : undefined)

  const buttonClasses = $derived([
    componentStyles.button.base,
    componentStyles.button.sizes[size],
    componentStyles.button.variations[variation],
    className
  ].join(' '))
</script>

{#if href}
  {#if LinkComponent}
    <svelte:component
      this={LinkComponent}
      {href}
      {target}
      {rel}
      class={buttonClasses}
    >
      {#if icon}{@render icon()}{/if}
      {#if text}<span>{text}</span>{/if}
    </svelte:component>
  {:else}
    <a
      {href}
      {target}
      {rel}
      class={buttonClasses}
    >
      {#if icon}{@render icon()}{/if}
      {#if text}<span>{text}</span>{/if}
    </a>
  {/if}
{/if}

// src/components/react/content/Button.tsx
import React from "react";
import * as Icons from "lucide-react";
import { componentStyles, cn } from "../../shared";
import { useDocuBook } from "../context";

type ButtonProps = {
  icon?: keyof typeof Icons;
  text?: string;
  href: string;
  target?: "_blank" | "_self" | "_parent" | "_top";
  size?: "sm" | "md" | "lg";
  variation?: "primary" | "accent" | "outline" | "ghost" | "link";
  className?: string;
};

const Button: React.FC<ButtonProps> = ({
  icon,
  text,
  href,
  target,
  size = "md",
  variation = "primary",
  className,
}) => {
  const { Link } = useDocuBook();

  const buttonClasses = cn(
    componentStyles.button.base,
    componentStyles.button.sizes[size],
    componentStyles.button.variations[variation],
    className
  );

  const Icon = icon ? (Icons[icon] as React.FC<{ className?: string }>) : null;

  return (
    <Link
      href={href}
      target={target}
      rel={target === "_blank" ? "noopener noreferrer" : undefined}
      className={buttonClasses}
    >
      {Icon && <Icon className="mr-2 h-4 w-4" />}
      {text && <span>{text}</span>}
    </Link>
  );
};

export default Button;
