// src/components/svelte/content/Copy.svelte
<script lang="ts">
  import { componentStyles } from '../../shared';
  import { Check, Copy as CopyIcon } from 'lucide-svelte';

  let content = $props<string>('');

  let isCopied = $state(false);

  async function handleCopy() {
    if (content) {
      await navigator.clipboard.writeText(content);
      isCopied = true;
      setTimeout(() => {
        isCopied = false;
      }, 2000);
    }
  }
</script>

<button
  type="button"
  class={componentStyles.copy.base + ' cursor-copy'}
  onclick={handleCopy}
>
  {#if isCopied}
    <Check class={componentStyles.copy.icon} />
  {:else}
    <CopyIcon class={componentStyles.copy.icon} />
  {/if}
</button>

// src/components/react/content/Copy.tsx
'use client'

import React, { useState } from 'react'
import { Check, Copy as CopyIcon } from 'lucide-react'
import { componentStyles, cn } from '../../shared'

type CopyProps = {
  content: string;
};

const Copy: React.FC<CopyProps> = ({ content }) => {
  const [isCopied, setIsCopied] = useState(false);

  async function handleCopy() {
    await navigator.clipboard.writeText(content);
    setIsCopied(true);

    setTimeout(() => {
      setIsCopied(false);
    }, 2000);
  }

  return (
    <button
      type="button"
      className={cn(componentStyles.copy.base, 'cursor-copy')}
      onClick={handleCopy}
    >
      {isCopied ? (
        <Check className={componentStyles.copy.icon} />
      ) : (
        <CopyIcon className={componentStyles.copy.icon} />
      )}
    </button>
  );
};

export default Copy;
