// src/components/svelte/content/Link.svelte
<script lang="ts">
  import { componentStyles } from '../../shared'
  import { getDocuBook } from '../../../adapters/svelte'

  let { href = '', className = '' }: { href?: string; className?: string } = $props()

  let LinkComponent = $derived(getDocuBook()?.Link || null)

  const linkClasses = $derived([
    componentStyles.link.base,
    className
  ].join(' '))
</script>

{#if href}
  {#if LinkComponent}
    <svelte:component
      this={LinkComponent}
      {href}
      target="_blank"
      rel="noopener noreferrer"
      class={linkClasses}
    >
      <slot />
    </svelte:component>
  {:else}
    <a
      {href}
      target="_blank"
      rel="noopener noreferrer"
      class={linkClasses}
    >
      <slot />
    </a>
  {/if}
{/if}

// src/components/react/content/Link.tsx
import React from 'react'
import { componentStyles, cn } from '../../shared'
import { useDocuBook } from '../context'

interface DocuLinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
    href: string
}

/**
 * Framework-agnostic Link component.
 * Named `DocuLink` to avoid collision with native HTML `<link>` in MDX.
 */
export function DocuLink({ href, className, ...props }: DocuLinkProps) {
    const { Link } = useDocuBook()

    if (!href) return null

    return (
        <Link
            href={href}
            target="_blank"
            rel="noopener noreferrer"
            className={cn(componentStyles.link.base, className)}
            {...props}
        />
    )
}

export default DocuLink
