// src/components/react/ui/Checkbox.tsx
'use client'

import React from 'react'
import * as CheckboxPrimitive from '@radix-ui/react-checkbox'
import { Check } from 'lucide-react'
import { componentStyles, cn } from '../../shared'

interface CheckboxProps extends React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root> {
  className?: string
}

const Checkbox = React.forwardRef<React.ElementRef<typeof CheckboxPrimitive.Root>, CheckboxProps>(
  ({ className, ...props }, ref) => (
    <CheckboxPrimitive.Root
      ref={ref}
      className={cn(componentStyles.checkbox.base, className)}
      {...props}
    >
      <CheckboxPrimitive.Indicator className={componentStyles.checkbox.indicator}>
        <Check className="h-4 w-4" />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  )
)
Checkbox.displayName = CheckboxPrimitive.Root.displayName

export { Checkbox }

// src/components/svelte/ui/Checkbox.svelte
<script lang="ts">
  import { Checkbox as BitsCheckbox } from 'bits-ui';
  import { Check } from 'lucide-svelte';
  import { componentStyles } from '../../shared';

  type CheckboxProps = BitsCheckbox.RootProps & {
    class?: string;
  };

  let { checked = $bindable(false), disabled = false, class: className = '', ...restProps }: CheckboxProps = $props();
</script>

<BitsCheckbox.Root bind:checked {disabled} class={className || componentStyles.checkbox.base} {...restProps}>
  <BitsCheckbox.Indicator class={componentStyles.checkbox.indicator}>
    <Check class="h-4 w-4" />
  </BitsCheckbox.Indicator>
</BitsCheckbox.Root>
