// src/components/vue/Separator.vue
<script setup lang="ts">
import { componentStyles } from '../shared'

interface SeparatorProps {
  className?: string
  orientation?: 'horizontal' | 'vertical'
  decorative?: boolean
}

const props = withDefaults(defineProps<SeparatorProps>(), {
  orientation: 'horizontal',
  decorative: true
})
</script>

<template>
  <div
    :class="[
      componentStyles.separator.base,
      orientation === 'horizontal' ? componentStyles.separator.horizontal : componentStyles.separator.vertical,
      props.className
    ]"
    :data-orientation="orientation"
    :role="decorative ? 'none' : 'separator'"
  />
</template>

<script lang="ts">
export default {
  name: 'Separator'
}
</script>

// src/components/svelte/ui/Separator.svelte
<script lang="ts">
  import { componentStyles } from '../../shared';

  type SeparatorProps = {
    orientation?: 'horizontal' | 'vertical';
    class?: string;
  };

  let { orientation = 'horizontal', class: className = '', ...restProps }: SeparatorProps = $props();
</script>

{#if orientation === 'horizontal'}
  <div class={className || componentStyles.separator.horizontal} {...restProps}></div>
{:else}
  <div class={className || componentStyles.separator.vertical} {...restProps}></div>
{/if}
