// src/components/vue/Accordion.vue
<script setup lang="ts">
import { ref, provide } from 'vue'
import { ChevronRight } from 'lucide-vue-next'
import type { AccordionProps } from '../shared/types'

const props = withDefaults(defineProps<AccordionProps>(), {
  defaultOpen: false
})

const isOpen = ref(props.defaultOpen)

const toggle = () => {
  isOpen.value = !isOpen.value
}

provide('accordionGroup', { inGroup: false })
</script>

<template>
  <div class="border rounded-lg shadow-sm">
    <button
      type="button"
      @click="toggle"
      class="flex items-center gap-2 w-full px-4 py-3 transition-colors bg-muted/40 dark:bg-muted/20 hover:bg-muted/70 dark:hover:bg-muted/70 cursor-pointer text-start"
    >
      <ChevronRight
        class="w-4 h-4 text-muted-foreground transition-transform duration-200 flex-shrink-0"
        :class="{ 'rotate-90': isOpen }"
      />
      <slot name="icon" />
      <h3 class="font-medium text-base text-foreground !m-0">{{ title }}</h3>
    </button>

    <div v-if="isOpen" class="px-4 py-3 dark:bg-muted/10 bg-muted/15">
      <slot />
    </div>
  </div>
</template>

// src/components/Accordion.tsx
"use client";

import { ReactNode, useState, useContext } from 'react';
import { ChevronRight } from 'lucide-react';
import * as Icons from "lucide-react";
import clsx from 'clsx';
import { AccordionGroupContext } from './AccordionContext';

type AccordionProps = {
    title: string;
    children?: ReactNode;
    defaultOpen?: boolean;
    icon?: keyof typeof Icons;
};

const Accordion: React.FC<AccordionProps> = ({
    title,
    children,
    defaultOpen = false,
    icon,
}: AccordionProps) => {
    const groupContext = useContext(AccordionGroupContext);
    const isInGroup = groupContext?.inGroup === true;
    const [isOpen, setIsOpen] = useState(defaultOpen);
    const Icon = icon ? (Icons[icon] as React.FC<{ className?: string }>) : null;

    return (
        <div
            className={clsx(
                !isInGroup && "border rounded-lg shadow-sm",
                isInGroup && "border-b last:border-b-0 border-border"
            )}
        >
            <button
                type="button"
                onClick={() => setIsOpen(!isOpen)}
                className="flex items-center gap-2 w-full px-4 py-3 transition-colors bg-muted/40 dark:bg-muted/20 hover:bg-muted/70 dark:hover:bg-muted/70 cursor-pointer text-start"
            >
                <ChevronRight
                    className={clsx(
                        "w-4 h-4 text-muted-foreground transition-transform duration-200 flex-shrink-0",
                        isOpen && "rotate-90"
                    )}
                />
                {Icon && <Icon className="text-foreground w-4 h-4 flex-shrink-0" />}
                <h3 className="font-medium text-base text-foreground !m-0">{title}</h3>
            </button>

            {isOpen && (
                <div className="px-4 py-3 dark:bg-muted/10 bg-muted/15">
                    {children}
                </div>
            )}
        </div>
    );
};

export default Accordion;
