// src/components/svelte/Card.svelte
<script lang="ts">
  import { useDocuBook } from '../../adapters/svelte'
  import { get } from 'svelte/store'
  
  export let title: string
  export let href: string = ''
  export let horizontal: boolean = false
  export let icon: string = ''
  export let children: any = undefined
  
  const { Link } = useDocuBook()
  const LinkComponent = get(Link) as any
  
  $: containerClass = `border rounded-lg shadow-sm p-4 transition-all duration-200 bg-card text-card-foreground border-border hover:bg-accent/5 hover:border-accent/30 flex gap-2 ${horizontal ? 'flex-row items-center gap-1' : 'flex-col space-y-1'}`
</script>

{#if href}
  <svelte:component this={LinkComponent} {href} class="no-underline block">
    <div class={containerClass}>
      <slot name="icon" />
      <div class="flex-1 min-w-0 my-auto h-full">
        <span class="text-base font-semibold text-foreground">{title}</span>
        <div class="text-sm text-muted-foreground">
          <slot />
        </div>
      </div>
    </div>
  </svelte:component>
{:else}
  <div class={containerClass}>
    <slot name="icon" />
    <div class="flex-1 min-w-0 my-auto h-full">
      <span class="text-base font-semibold text-foreground">{title}</span>
      <div class="text-sm text-muted-foreground">
        <slot />
      </div>
    </div>
  </div>
{/if}

// src/components/Card.tsx
import React, { ReactNode } from 'react';
import * as Icons from 'lucide-react';
import clsx from 'clsx';
import { useDocuBook } from './context';

type IconName = keyof typeof Icons;

interface CardProps {
  title: string;
  icon?: IconName;
  href?: string;
  horizontal?: boolean;
  children: ReactNode;
  className?: string;
}

export const Card: React.FC<CardProps> = ({ title, icon, href, horizontal, children, className }) => {
  const { Link } = useDocuBook();
  const Icon = icon ? (Icons[icon] as React.FC<{ className?: string }>) : null;

  const content = (
    <div
      className={clsx(
        "border rounded-lg shadow-sm p-4 transition-all duration-200",
        "bg-card text-card-foreground border-border",
        "hover:bg-accent/5 hover:border-accent/30",
        "flex gap-2",
        horizontal ? "flex-row items-center gap-1" : "flex-col space-y-1",
        className
      )}
    >
      {Icon && <Icon className="w-5 h-5 text-primary flex-shrink-0" />}
      <div className="flex-1 min-w-0 my-auto h-full">
        <span className="text-base font-semibold text-foreground">{title}</span>
        <div className="text-sm text-muted-foreground -mt-3">{children}</div>
      </div>
    </div>
  );

  return href ? <Link className="no-underline block" href={href}>{content}</Link> : content;
};

export default Card;
