// src/components/vue/Copy.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Check, Copy as CopyIcon } from 'lucide-vue-next'

const props = defineProps<{ content: string }>()
const isCopied = ref(false)

async function handleCopy() {
  await navigator.clipboard.writeText(props.content)
  isCopied.value = true
  setTimeout(() => isCopied.value = false, 2000)
}
</script>

<template>
  <button
    type="button"
    class="inline-flex items-center justify-center px-2 py-1 text-xs font-medium border rounded transition-colors bg-muted hover:bg-muted/70 border-border cursor-copy"
    @click="handleCopy"
  >
    <Check v-if="isCopied" class="w-3 h-3" />
    <CopyIcon v-else class="w-3 h-3" />
  </button>
</template>

// src/components/react/Copy.tsx
import React, { useState } from "react";
import { Check, Copy as CopyIcon } from "lucide-react";

type CopyProps = {
  content: string;
};

const Copy: React.FC<CopyProps> = ({ content }) => {
  const [isCopied, setIsCopied] = useState(false);

  async function handleCopy() {
    await navigator.clipboard.writeText(content);
    setIsCopied(true);

    setTimeout(() => {
      setIsCopied(false);
    }, 2000);
  }

  return (
    <button
      type="button"
      className="inline-flex items-center justify-center px-2 py-1 text-xs font-medium border rounded transition-colors bg-muted hover:bg-muted/70 border-border cursor-copy"
      onClick={handleCopy}
    >
      {isCopied ? (
        <Check className="w-3 h-3" />
      ) : (
        <CopyIcon className="w-3 h-3" />
      )}
    </button>
  );
};

export default Copy;
