// src/components/vue/Card.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { CardProps } from '../shared/types'
import { useDocuBook } from '../../adapters/vue'

const props = defineProps<CardProps>()

const { Link } = useDocuBook()

const containerClass = computed(() => [
  'border rounded-lg shadow-sm p-4 transition-all duration-200',
  'bg-card text-card-foreground border-border',
  'hover:bg-accent/5 hover:border-accent/30',
  'flex gap-2',
  props.horizontal ? 'flex-row items-center gap-1' : 'flex-col space-y-1',
  props.className
])
</script>

<template>
  <component :is="href ? Link : 'div'" :href="href" :class="[!href && 'no-underline block']">
    <div :class="containerClass">
      <slot name="icon" />
      <div class="flex-1 min-w-0 my-auto h-full">
        <span class="text-base font-semibold text-foreground">{{ title }}</span>
        <div class="text-sm text-muted-foreground">
          <slot />
        </div>
      </div>
    </div>
  </component>
</template>

// src/components/svelte/content/Card.svelte
<script lang="ts">
  import { componentStyles } from '../../shared';
  import { getDocuBook } from '../../../adapters/svelte';

  let title = $props<string>('');
  let href = $props<string>('');
  let horizontal = $props<boolean>(false);
  let icon = $props<string>('');
  let className = $props<string>('');

  let LinkComponent = $derived<any>(getDocuBook()?.Link || null);

  const containerClass = $derived([
    'border rounded-lg shadow-sm p-4 transition-all duration-200 bg-card text-card-foreground border-border hover:bg-accent/5 hover:border-accent/30',
    horizontal ? 'flex-row items-center gap-1' : 'flex-col space-y-1',
    className
  ].join(' '));
</script>

{#if href}
  {#if LinkComponent}
    <svelte:component this={LinkComponent} {href} class="no-underline block">
      <div class={containerClass}>
        <slot name="icon" />
        <div class="flex-1 min-w-0 my-auto h-full">
          <span class="text-base font-semibold text-foreground">{title}</span>
          <div class="text-sm text-muted-foreground">
            <slot />
          </div>
        </div>
      </div>
    </svelte:component>
  {:else}
    <a {href} class="no-underline block">
      <div class={containerClass}>
        <slot name="icon" />
        <div class="flex-1 min-w-0 my-auto h-full">
          <span class="text-base font-semibold text-foreground">{title}</span>
          <div class="text-sm text-muted-foreground">
            <slot />
          </div>
        </div>
      </div>
    </a>
  {/if}
{:else}
  <div class={containerClass}>
    <slot name="icon" />
    <div class="flex-1 min-w-0 my-auto h-full">
      <span class="text-base font-semibold text-foreground">{title}</span>
      <div class="text-sm text-muted-foreground">
        <slot />
      </div>
    </div>
  </div>
{/if}
