// src/components/react/content/Pre.tsx
'use client'

import React, { type ComponentProps } from 'react'
import { componentStyles, cn } from '../../shared'
import Copy from './Copy'

type PreProps = ComponentProps<'pre'> & {
    raw?: string
    'data-title'?: string
}

export function Pre({ children, raw, ...rest }: PreProps) {
    const { 'data-title': title, className, ...restProps } = rest
    const hasTitle = !!title

    return (
        <div className={cn(
            componentStyles.pre.base,
            'border border-border rounded-lg my-4 overflow-hidden'
        )}>
            <div className="absolute top-2 right-2 z-10">
                {raw && <Copy content={raw} />}
            </div>
            {hasTitle && (
                <div className="flex items-center gap-2 px-4 py-2 text-sm font-medium border-b border-border bg-muted/50">
                    <span>{title}</span>
                </div>
            )}
            <div className="overflow-x-auto">
                <pre className={cn(hasTitle && componentStyles.pre.withCopy, className)} {...restProps}>
                    {children}
                </pre>
            </div>
        </div>
    )
}

export default Pre

// src/components/svelte/content/Pre.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { componentStyles } from '../../shared'
  import { Check, Copy as CopyIcon } from 'lucide-svelte'

  let { 
    raw = '', 
    dataTitle = '', 
    className = '',
    children
  }: { 
    raw?: string; 
    dataTitle?: string; 
    className?: string;
    children: Snippet
  } = $props()

  let isCopied = $state(false)

  async function handleCopy() {
    if (raw) {
      await navigator.clipboard.writeText(raw)
      isCopied = true
      setTimeout(() => {
        isCopied = false
      }, 2000)
    }
  }

  const hasTitle = $derived(!!dataTitle)
</script>

<div class={componentStyles.pre.base + ' border border-border rounded-lg my-4 overflow-hidden'}>
  <div class="absolute top-2 right-2 z-10">
    {#if raw}
      <button
        type="button"
        class={componentStyles.copy.base + ' cursor-copy'}
        onclick={handleCopy}
      >
        {#if isCopied}
          <Check class={componentStyles.copy.icon} />
        {:else}
          <CopyIcon class={componentStyles.copy.icon} />
        {/if}
      </button>
    {/if}
  </div>
  {#if hasTitle}
    <div class="flex items-center gap-2 px-4 py-2 text-sm font-medium border-b border-border bg-muted/50">
      <span>{dataTitle}</span>
    </div>
  {/if}
  <div class="overflow-x-auto">
    <pre class:pr-12={hasTitle} class={className}>
      {@render children()}
    </pre>
  </div>
</div>
