// src/components/react/ui/Tooltip.tsx
'use client'

import React from 'react'
import * as TooltipPrimitive from '@radix-ui/react-tooltip'
import { componentStyles, cn } from '../../shared'

const TooltipProvider = TooltipPrimitive.Provider

const Tooltip = TooltipPrimitive.Root

const TooltipTrigger = TooltipPrimitive.Trigger

interface TooltipContentProps extends React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content> {
  className?: string
}

const TooltipContent = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Content>,
  TooltipContentProps
>(({ className, sideOffset = 4, ...props }, ref) => (
  <TooltipPrimitive.Content
    ref={ref}
    sideOffset={sideOffset}
    className={cn(componentStyles.tooltip.content, className)}
    {...props}
  />
))
TooltipContent.displayName = TooltipPrimitive.Content.displayName

export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider }

// src/components/svelte/content/Tooltip.svelte
<script lang="ts">
  import { componentStyles } from '../../shared';
  import TooltipRoot from '../ui/Tooltip.svelte';
  import TooltipTrigger from '../ui/TooltipTrigger.svelte';
  import TooltipContent from '../ui/TooltipContent.svelte';

  let className = $props<string>('');
</script>

<TooltipRoot>
  <TooltipTrigger class={className}>
    <slot name="trigger" />
  </TooltipTrigger>
  <TooltipContent>
    <slot />
  </TooltipContent>
</TooltipRoot>
